# Generated by Django 4.2.7 on 2024-05-04 10:57

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_achievementcondition_cosmetic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselevel',
            name='inputs',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='exerciselevel',
            name='outputs',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='exerciselevel',
            name='truth_table',
            field=django_jsonform.models.fields.ArrayField(base_field=django_jsonform.models.fields.ArrayField(base_field=models.BooleanField(), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='participant',
            name='input_types',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='participant',
            name='output_types',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None),
        ),
    ]
