# Generated by Django 4.2.7 on 2024-05-06 17:01

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_exerciselevel_inputs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='prerequisites',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='scenario', chained_model_field='scenario', to='api.level', verbose_name='Prerequisites'),
        ),
    ]
