# Generated by Django 4.2.7 on 2024-05-08 11:53

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_level_prerequisites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='score',
            new_name='stars',
        ),
        migrations.AddField(
            model_name='exerciselevel',
            name='time_goal',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='time',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='level',
            name='prerequisites',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='scenario', chained_model_field='scenario', horizontal=True, to='api.level', verbose_name='Prerequisites'),
        ),
    ]
