# Generated by Django 4.2.7 on 2024-05-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_avatar_colorpalette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='colorPalette',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
