# Generated by Django 4.2.7 on 2024-05-13 12:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_progress_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
            preserve_default=False,
        ),
    ]
