# Generated by Django 4.2.7 on 2024-05-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_level_level_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='level_type',
        ),
        migrations.AddField(
            model_name='exerciselevel',
            name='end_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciselevel',
            name='start_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
