# Generated by Django 4.2.7 on 2024-05-14 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_level_level_type_exerciselevel_end_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('visual', models.ImageField(upload_to='visuals/')),
            ],
        ),
        migrations.RenameField(
            model_name='informationlevel',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='informationlevel',
            name='visual',
        ),
    ]
