# Generated by Django 4.2.7 on 2024-05-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_visual_rename_text_informationlevel_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselevel',
            name='challenge',
            field=models.BooleanField(default=False),
        ),
    ]
