# Generated by Django 4.2.7 on 2024-05-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_scenarioprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='api.scenario'),
        ),
    ]
