# Generated by Django 4.2.7 on 2024-05-15 14:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_scenario_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='star_details',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='progress',
            name='stars',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
