# Generated by Django 4.2.7 on 2024-05-15 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_progress_star_details_alter_progress_stars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselevel',
            name='gates',
        ),
        migrations.AddField(
            model_name='exerciselevel',
            name='gates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
        ),
    ]
