# Generated by Django 4.2.7 on 2024-05-15 15:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_exerciselevel_gates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselevel',
            name='gates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None),
        ),
    ]
