# Generated by Django 4.2.7 on 2024-05-17 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_exerciselevel_gates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementcondition',
            name='parameters',
        ),
        migrations.AddField(
            model_name='achievementcondition',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.level'),
        ),
        migrations.AddField(
            model_name='achievementcondition',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.scenario'),
        ),
        migrations.AddField(
            model_name='achievementcondition',
            name='stars',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.achievementcondition'),
        ),
        migrations.AlterField(
            model_name='achievementcondition',
            name='condition_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Level Completion'), (2, 'Scenario Completion'), (3, 'Star Collection')]),
        ),
    ]
