# Generated by Django 4.2.7 on 2024-05-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_achievementcondition_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
