# Generated by Django 4.2.7 on 2024-05-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_progress_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementcondition',
            name='condition_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Level Completion'), (2, 'Level Retry'), (3, 'Scenario Completion'), (4, 'Star Collection')]),
        ),
    ]
