# Generated by Django 4.2.7 on 2024-05-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='submissions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
