# Generated by Django 4.2.7 on 2024-05-26 18:04

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_attempts_progress_completions'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationlevel',
            name='guides',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
