# Generated by Django 4.2.7 on 2024-05-26 18:37

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_informationlevel_guides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationlevel',
            name='guides',
            field=django_jsonform.models.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
    ]
