# Generated by Django 4.2.7 on 2024-05-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_informationlevel_guides'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='class_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.classroom'),
        ),
    ]
