# Generated by Django 4.2.7 on 2024-05-26 21:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_achievement_class_related'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementVisual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('visual', models.ImageField(upload_to='visuals/achievements/')),
            ],
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='visual',
        ),
        migrations.AddField(
            model_name='achievement',
            name='visual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.achievementvisual'),
        ),
    ]
