services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod       
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/backend/static
      - media_volume:/home/app/backend/media
    networks:
      - circuitnest
    env_file:
      - ./backend/.env.prod
      - ./backend/.env.secret
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    expose:
      - 80
    volumes:
      - ./frontend:/frontend
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    networks:
      - nginx-proxy_reverse-proxy
      - circuitnest
    environment:
      - VIRTUAL_HOST=circuitnest.mazyar.co.nl
    depends_on:
      - backend

  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - circuitnest
    env_file:
      - ./backend/.env.prod.db

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  circuitnest:
  nginx-proxy_reverse-proxy:
    external: true
