services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env.dev
      - ./backend/.env.secret
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
    volumes:
      - ./frontend/circuitnest:/app
      - /app/node_modules
    command: ["npm", "start"]
    environment:
       - WATCHPACK_POLLING=true
       - WDS_SOCKET_PORT=80

  db:
    image: postgres:16.2
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.dev.db

volumes:
  postgres_data_dev: